import { AiFillStar } from "react-icons/ai";

const data = [
  {
    id: 1,
    img: "https://p.kindpng.com/picc/s/212-2128924_nike-running-shoes-transparent-image-black-nike-shoes.png",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(100 reviews)",
    prevPrice: "$140,00",
    newPrice: "250",
    company: "Nike",
    color: "black",
    category: "sneakers",
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/61lSJ1IdQjL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(129 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
  },

  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/51TuhyzQ9QL._AC_SY395_.jpg",
    title: "New Balance Men's FuelCell 4040 V7 Molded Baseball Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(207 reviews)",
    prevPrice: "$240,00",
    newPrice: "205",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    title: "Adidas Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/61HMPtoCANL._AC_SY395_.jpg",
    title: "New Balance Men's Fresh Foam X 880 V13 Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$109,00",
    newPrice: "50",
    company: "New Balance",
    color: "white",
    category: "flats",
  },

  {
    id: 7,
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
  },

  {
    id: 8,
    img: "https://m.media-amazon.com/images/I/51NW9EK3phL._AC_SX395_.jpg",
    title: "Nike Men's Court Vision Lo Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
  },

  {
    id: 9,
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Adidas Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
  },

  {
    id: 10,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id: 11,
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
  },
  {
    id: 12,
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },
  {
    id: 13,
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id: 14,
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Double",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
  },

  {
    id: 15,
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
  },
  {
    id: 16,
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Checks Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
  },
  {
    id: 17,
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
  },
  {
    id: 18,
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
  },
  {
    id: 19,
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Nike",
    color: "black",
    category: "sandals",
  },
  {
    id: 20,
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
  },
  {
    id: 21,
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
  },
  {
    id: 22,
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
  },
  {
    id: 23,
    img: "https://m.media-amazon.com/images/I/71x7NX6Iw-L._AC_SX395_.jpg",
    title: "Nike Men's Downshifter Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(88 reviews)",
    prevPrice: "$150,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
  },

  {
    id: 24,
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
  },
  {
    id: 25,
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id: 26,
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Adidas Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
  },
  {
    id: 27,
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Adidas Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
  },
  {
    id: 28,
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Adidas Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
  },
  {
    id: 29,
    img: " https://m.media-amazon.com/images/I/51XPXEhM0BL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Adidas Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$149,00",
    newPrice: "140",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id: 30,
    img: " https://m.media-amazon.com/images/I/61BwndehQ-L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Womens Smashic Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$199,00",
    newPrice: "149",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id: 31,
    img: " https://m.media-amazon.com/images/I/51SymQudSKL._SY695_.jpg",
    title: "Smashic Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$199,00",
    newPrice: "149",
    company: "Puma",
    color: "white",
    category: "sneakers",
  },
  {
    id: 32,
    img: " https://m.media-amazon.com/images/I/51SymQudSKL._SY695_.jpg",
    title: "New Balance Men's 480 V1",
    star: <AiFillStar className="rating-star" />,
    reviews: "(111 reviews)",
    prevPrice: "$299,00",
    newPrice: "149",
    company: "New Balance",
    color: "Blue",
    category: "sneakers",
  },
  {
    id: 33,
    img: "https://m.media-amazon.com/images/I/51uH+XqBtnL._AC_SY395_.jpg",
    title: "New Balance men's M880l14 Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(155 reviews)",
    prevPrice: "$299,00",
    newPrice: "139",
    company: "New Balance",
    color: "Blue",
    category: "sneakers",
  },
  {
    id: 34,
    img: "https://m.media-amazon.com/images/I/71XkumNTfYL._AC_SX395_.jpg",
    title: "New Balance Men's Freezelx V4 Lacrosse Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(199 reviews)",
    prevPrice: "$199,00",
    newPrice: "159",
    company: "New Balance",
    color: "red",
    category: "sneakers",
  },
  {
    id: 35,
    img: "https://m.media-amazon.com/images/I/31Smy1tvZLL._AC_SY500_.jpg",
    title: "Reebok Unisex-Adult Classic Leather",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$599,00",
    newPrice: "959",
    company: "Reebok",
    color: "white",
    category: "sneakers",
  },
  {
    id: 36,
    img: "https://m.media-amazon.com/images/I/31Smy1tvZLL._AC_SY500_.jpg",
    title: "Reebok Men's Classic Harman Run",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$499,00",
    newPrice: "959",
    company: "Reebok",
    color: "black",
    category: "sneakers",
  },
  {
    id: 36,
    img: "https://m.media-amazon.com/images/I/613jDjVuaKL._AC_SY535_.jpg",
    title: "Reebok Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$59,00",
    newPrice: "49",
    company: "Reebok",
    color: "green",
    category: "sneakers",
  },
  {
    id: 37,
    img: "https://m.media-amazon.com/images/I/81Hy7MfhRxL._AC_SX395_.jpg",
    title: "Reebok unisex-adult Lx2200",
    star: <AiFillStar className="rating-star" />,
    reviews: "(99 reviews)",
    prevPrice: "$99,00",
    newPrice: "55",
    company: "Reebok",
    color: "red",
    category: "sneakers",
  },
  {
    id: 38,
    img: "https://m.media-amazon.com/images/I/71fXr16ZvvL._AC_SY395_.jpg",
    title: "Converse Unisex Chuck Taylor All Star Canvas High Top ",
    star: <AiFillStar className="rating-star" />,
    reviews: "(988 reviews)",
    prevPrice: "$68,00",
    newPrice: "52",
    company: "Converse",
    color: "black",
    category: "sneakers",
  },
  {
    id: 39,
    img: "https://m.media-amazon.com/images/I/71HWDFnd3vL._AC_SX395_.jpg",
    title: "Converse Women's Chuck Taylor",
    star: <AiFillStar className="rating-star" />,
    reviews: "(788 reviews)",
    prevPrice: "$121,00",
    newPrice: "42",
    company: "Converse",
    color: "blue",
    category: "sneakers",
  },
  {
    id: 40,
    img: "https://m.media-amazon.com/images/I/51Ms132BK9L._AC_SY395_.jpg",
    title: "Fila Men's Speedserve Energized",
    star: <AiFillStar className="rating-star" />,
    reviews: "(88 reviews)",
    prevPrice: "$69,00",
    newPrice: "54",
    company: "Fila",
    color: "red",
    category: "sneakers",
  },
  {
    id: 41,
    img: "https://m.media-amazon.com/images/I/61NyoiQ0c0L._AC_SX500_.jpg",
    title: "Fila MB Mens Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(88 reviews)",
    prevPrice: "$150,00",
    newPrice: "99",
    company: "Fila",
    color: "yellow",
    category: "sneakers",
  },
  {
    id: 42,
    img: "https://static-01.daraz.com.np/p/27c62fff324584dad63c15754c8c30c8.jpg_300x0q75.webp",
    title: "Goldstar Dash 01 Casule Shoes For Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(998 reviews)",
    prevPrice: "$750,00",
    newPrice: "699",
    company: "Goldstar",
    color: "black",
    category: "sneakers",
  },
  {
    id: 43,
    img: "https://np-live-21.slatic.net/kf/S53ad93fb2172485daadc30ae02f550d92.jpg_300x0q75.webp",
    title: "Goldstar White Color Dash 10 Casual Shoes For Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(878 reviews)",
    prevPrice: "$190,00",
    newPrice: "99",
    company: "Goldstar",
    color: "white",
    category: "sneakers",
  },
];

export default data;
